name: Self Hosted Test

on:
  push:

jobs:
  test:
    runs-on: self-hosted

    steps:
      - name: Print hostname
        run: hostname

      - name: Print current user
        run: whoami

      - name: Print OS
        run: uname -a
