name: Job Outputs Demo

on:
  push:

jobs:
  generate-date:
    runs-on: ubuntu-latest

    outputs:
      today: ${{ steps.date.outputs.today }}

    steps:
      - name: Get today's date
        id: date
        run: echo "today=$(date +'%Y-%m-%d')" >> "$GITHUB_OUTPUT"

  print-date:
    runs-on: ubuntu-latest
    needs: generate-date

    steps:
      - name: Print the date received from previous job
        run: echo "Today's date is ${{ needs.generate-date.outputs.today }}"
