name: Multi Job Workflow

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Build the application
        run: echo "Building the app"

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Run tests
        run: echo "Running tests"

  deploy:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Deploy the application
        run: echo "Deploying"
