name: Secrets Demo

on:
  push:
    paths:
      - ".github/workflows/secrets-demo.yml"

jobs:
  secret-check:
    runs-on: ubuntu-latest

    steps:
      - name: Check if secret is set
        run: |
          if [ -n "${{ secrets.MY_SECRET_MESSAGE }}" ]; then
            echo "The secret is set: true"
          else
            echo "The secret is set: false"
          fi

      - name: Print secret
        run: echo "${{ secrets.MY_SECRET_MESSAGE }}"
