name: Secrets Environment Variables

on:
  push:
    paths:
      - ".github/workflows/secrets-env.yml"

jobs:
  docker-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Check Docker credentials
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_TOKEN: ${{ secrets.DOCER_TOKEN }}
        run: |
          if [ -n "$DOCKER_USERNAME" ]; then
             echo "Docker username is set: true"
          else
             echo "Docker username is set: false"
          fi

          if [ -n "$DOCKER_TOKEN" ]; then
            echo "Docker token is set: true"
          else
            echo "Docker token is set: false"
          fi
